-- ==========================================================
-- SCHEMA DATABASE DIGILIBRARY UNTUK SUPABASE (POSTGRESQL)
-- ==========================================================

-- Hapus tabel lama jika sudah ada (Opsional - Berhati-hatilah)
-- DROP TABLE IF EXISTS public.borrowings;
-- DROP TABLE IF EXISTS public.books;
-- DROP TABLE IF EXISTS public.profiles;
-- DROP TABLE IF EXISTS public.categories;

-- 1. TABEL KATEGORI
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL PROFILES (Tautkan dengan tabel auth.users bawaan Supabase)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL BUKU
CREATE TABLE IF NOT EXISTS public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    cover_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL PEMINJAMAN
CREATE TABLE IF NOT EXISTS public.borrowings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
    borrow_date DATE NOT NULL DEFAULT CURRENT_DATE,
    return_date DATE NOT NULL,
    actual_return_date DATE DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'borrowed' CHECK (status IN ('pending', 'borrowed', 'returned', 'overdue', 'return_pending')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- AUTO-SYNC PROFIL PENGGUNA BARU DARI AUTH.USERS
-- ==========================================================
-- Fungsi ini akan otomatis berjalan saat user mendaftar melalui Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'User Baru'),
    new.email,
    'user' -- Secara default, pendaftar baru adalah 'user'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger untuk menjalankan fungsi di atas setelah insert di auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================================
-- SEED DATA AWAL (Kategori & Buku Contoh)
-- ==========================================================

-- Seed Kategori
INSERT INTO public.categories (name) VALUES
    ('Fiksi'),
    ('Non-Fiksi'),
    ('Sains'),
    ('Sejarah'),
    ('Teknologi'),
    ('Fantasi'),
    ('Sastra')
ON CONFLICT (name) DO NOTHING;

-- Seed Buku
INSERT INTO public.books (title, author, category_id, stock, cover_url, description)
VALUES
    (
        'Pengantar Pemrograman',
        'Budi Santoso',
        (SELECT id FROM public.categories WHERE name = 'Teknologi' LIMIT 1),
        10,
        'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=300',
        'Buku dasar pemrograman untuk pemula dengan contoh JavaScript dan PHP.'
    ),
    (
        'Sejarah Perpustakaan Modern',
        'Siti Aminah',
        (SELECT id FROM public.categories WHERE name = 'Non-Fiksi' LIMIT 1),
        5,
        'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300',
        'Ringkasan perkembangan sistem perpustakaan dari era klasik hingga digital.'
    ),
    (
        'Desain UI/UX untuk Aplikasi',
        'Indra Wijaya',
        (SELECT id FROM public.categories WHERE name = 'Teknologi' LIMIT 1),
        7,
        'https://images.unsplash.com/photo-1541462608141-2ffb16dfd8e0?w=300',
        'Panduan membuat tampilan aplikasi modern dan responsif menggunakan desain SaaS.'
    )
ON CONFLICT DO NOTHING;
